version: "3.1"

services:
  adminer:
    image: adminer:4.2.5-standalone
    restart: always
    ports:
      - 80:8080
    networks:
      - frontend
      - backend

  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - backend

networks:
  frontend:
  backend:
